### ISSUE TITLE
All roster statuses visible on the site

### ISSUE THREAD

**Issue by jeremyjbowers** [jeremyjbowers/npl#1]
Currently denoted with colors in the sheet
- [ ] Club option
- [ ] Vesting option (becomes club option if vesting terms are not met, unless noted that it is a player option)
- [ ] Mutual option
- [ ] Player option
- [ ] Player opt-out clause
- [ ] Arbitration salary
- [ ] On waivers
- [ ] Eligible to be extended by current team for amount of years specified. No highlight means not eligible
- [ ] Player is ineligible to be recalled to the majors until the listed date arrives in NPL.
- [ ] Pending free agent
- [ ] Contract signed; pending contract terms

**Comment by baldrige** [comment]
Also, the items from the STA column: 

- [ ] Player has been outrighted
- [ ] Player has previously received a qualifying offer
- [ ] Is a rule 5 draft selection this season
